# Generated by Django 3.1.7 on 2021-03-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bid_price',
            field=models.IntegerField(blank=True, default=23),
            preserve_default=False,
        ),
    ]
