# Generated by Django 3.1.7 on 2021-03-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210326_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bid_status',
            field=models.BooleanField(default=0),
        ),
    ]
